// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "0960fe89-9752-4470-97dd-80f6b9fff9bb");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1550230653);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1550230773);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1550230173);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1550230413);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1550230293);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1550230533);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1550231013);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1550230893);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1550230144);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4061dafa-2cd4-4d5e-9fd1-8223e264c36e}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1550185200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1550231996278");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1550233782278");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1550230156832");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1550233756832");
user_pref("browser.search.region", "NG");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1550230149");
user_pref("browser.slowStartup.averageTime", 12827);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1550230153616");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "5ca1d7c97d814ed6be5dbf9cd038579b");
user_pref("extensions.blocklist.lastModified", "Fri, 08 Feb 2019 12:03:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1550230654);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{d0e62b5d-47be-4741-bd84-84674a32e91f}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"00b7c3dc-9594-44d5-8abf-57d7dc8dd685\",\"screenshots@mozilla.org\":\"89da4b06-de26-41af-8edc-4f24487eb58c\",\"webcompat-reporter@mozilla.org\":\"a09b21a8-272d-4fb4-a56a-9bdcec757ac3\",\"webcompat@mozilla.org\":\"983042bf-b9af-4c7f-a56f-743e74ffddc7\",\"fxmonitor@mozilla.org\":\"c023f8d1-8d79-411e-951a-04cabf45d837\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1550230306);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1550230305);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "fb0d6d13-952c-4ed4-8bdc-f974db1702e2");
user_pref("security.sandbox.plugin.tempDirSuffix", "7e56fc92-127c-4976-98e6-8537182dc367");
user_pref("services.blocklist.addons.checked", 1550230830);
user_pref("services.blocklist.gfx.checked", 1550230830);
user_pref("services.blocklist.onecrl.checked", 1550230830);
user_pref("services.blocklist.pinning.checked", 1550230830);
user_pref("services.blocklist.plugins.checked", 1550230830);
user_pref("services.settings.clock_skew_seconds", -297);
user_pref("services.settings.last_etag", "\"1550159961968\"");
user_pref("services.settings.last_update_seconds", 1550230830);
user_pref("services.settings.main.language-dictionaries.last_check", 1550230830);
user_pref("services.settings.main.onboarding.last_check", 1550230830);
user_pref("services.settings.main.sites-classification.last_check", 1550230830);
user_pref("services.settings.main.tippytop.last_check", 1550230830);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1550230136);
user_pref("toolkit.telemetry.cachedClientID", "1d0ad9d2-e463-4d9d-a6cd-1d98226827f6");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
